# Generated by Django 2.0.1 on 2018-02-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('property_address_line_1', models.CharField(max_length=50)),
                ('property_address_line_2', models.CharField(max_length=50)),
                ('property_address_line_3', models.CharField(max_length=50)),
                ('property_address_line_4', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=50)),
                ('tenant_name', models.CharField(max_length=50)),
                ('lease_start_date', models.DateField()),
                ('lease_end_date', models.DateField()),
                ('lease_years', models.IntegerField()),
                ('current_rent', models.IntegerField()),
            ],
        ),
    ]
