# Generated by Django 2.0.1 on 2018-02-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_address_line_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_address_line_3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
