# Generated by Django 2.0.1 on 2018-02-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20180211_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='current_rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
