# Generated by Django 2.0.1 on 2018-02-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20180212_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_address_line_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_address_line_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_address_line_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_address_line_4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='tenant_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_name',
            field=models.CharField(max_length=100),
        ),
    ]
